on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: ruby
          package-name: wafris
          bump-minor-pre-major: true
          version-file: "lib/wafris/version.rb"
          changelog-path: "Changes.md"
